#!/usr/bin/env bash

# Copyright 2018 Palo Alto Networks.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Download and extract Terraform utility in the deployment directory.
function getTerraform() {
  # Places terraform in /usr/local/bin dir.
  local T_VERSION='1.0.7/terraform_1.0.7_linux_amd64'
  local T_URL="https://releases.hashicorp.com/terraform/${T_VERSION}.zip"
  local T_DIR=/usr/local/bin
  local T_ZIP="${T_DIR}/terraform.zip"
  local T_EXE="${T_DIR}/terraform"

  if [ -e ${T_EXE} ]; then
    echo "${T_EXE} already exists. Exiting."
    return 0
  fi
  echo -n "Installing Terraform ..."
  pushd ${T_DIR} > /dev/null
  sudo curl -s -o "${T_ZIP}" "${T_URL}"
  sudo unzip -q "${T_ZIP}"
  sudo rm "${T_ZIP}"
  popd > /dev/null

  if [ -e ${T_EXE} ]; then
    echo " Done"
  else
    echo " Could not retrieve ${T_EXE}."
  fi
}

# Install Ansible package from apt repository.
function getAnsible() {
  local A_EXE="/usr/bin/ansible"

  if [ -e ${A_EXE} ]; then
    echo "${A_EXE} already exists. Exiting."
    return 0
  fi

  echo -n "Installing Ansible ..."
  sudo apt-get -y update &> setup.log
  sudo apt-get -y install software-properties-common &>> setup.log
  sudo apt-add-repository ppa:ansible/ansible -y &>> setup.log
  sudo apt-get -y update &>> setup.log
  sudo apt-get -y install ansible &>> setup.log

  if [ -e ${A_EXE} ]; then
    echo " Done"
  else
    echo " Could not retrieve ${A_EXE}."
  fi
}

# Install Python libraries.
function getPyLibs() {
  echo -n "Installing Python libraries ..."
  sudo pip install pandevice xmltodict &>> setup.log
  echo " Done"
}

# Main program
getTerraform
getAnsible
getPyLibs
